"""Classical ground truth for the Regev sampling distribution.

Computes the exact output distribution of the ideal (noiseless) Regev circuit,
so simulated counts can be validated against it via total variation distance.

The distribution is obtained from a single FFT of the relation-lattice
autocorrelation rather than one FFT per residue class -- see
`ideal_regev_distribution_array` for the derivation. That is what makes
instances beyond N = 77 tractable.
"""

from itertools import product

__all__ = [
    "ideal_regev_distribution",
    "ideal_regev_distribution_array",
    "total_variation_distance",
    "counts_to_distribution",
    "bitstring_to_regev_vector",
]

# Residue products reach N^2; int64 holds them while N^2 < 2^63. At or below
# this N the fast int64 path is used, above it an exact object-dtype fallback.
_MAX_MODULUS = 3_037_000_499  # floor(sqrt(2^63 - 1))


def _relation_autocorrelation(bases, N: int, d: int, M: int):
    """Weighted count of relation-lattice points, folded into Z_M^d.

    Returns an (M,)*d array A with

        A[e mod M] = sum over e in L, |e_i| < M, of prod_i (M - |e_i|)

    where L = { e in Z^d : prod a_i^{e_i} = 1 (mod N) } is the relation
    lattice. The weight prod_i (M - |e_i|) counts the ordered pairs (x, x')
    inside the box [0, M)^d with x - x' = e.
    """
    import numpy as np

    span = 2 * M - 1
    off = M - 1

    # Residue products reach N^2. int64 holds that while N^2 < 2^63; beyond
    # that, fall back to object arrays of Python ints, which are exact at any
    # width (slower, but M^d binds long before N does).
    res_dtype = np.int64 if N <= _MAX_MODULUS else object

    # tables[i][j] = a_i^(j - off) mod N, covering exponents -(M-1) .. M-1.
    tables = []
    for a in bases:
        inv_a = pow(a, -1, N)
        t = np.empty(span, dtype=res_dtype)
        t[off] = 1
        v = 1
        for e in range(1, M):
            v = v * a % N
            t[off + e] = v
        v = 1
        for e in range(1, M):
            v = v * inv_a % N
            t[off - e] = v
        tables.append(t)

    weights = np.array([M - abs(j - off) for j in range(span)], dtype=np.float64)
    folded = (np.arange(span) - off) % M

    # Residues and weights over dimensions 1..d-1, held as flat arrays. The
    # first dimension is iterated instead of materialised, which bounds peak
    # memory at span^(d-1) rather than span^d.
    if d == 1:
        rest_res = np.ones(1, dtype=res_dtype)
        rest_w = np.ones(1, dtype=np.float64)
        rest_idx = ()
    else:
        shape_rest = (span,) * (d - 1)
        rest_res = np.ones(shape_rest, dtype=res_dtype)
        rest_w = np.ones(shape_rest, dtype=np.float64)
        for i in range(1, d):
            sh = [1] * (d - 1)
            sh[i - 1] = span
            rest_res = rest_res * tables[i].reshape(sh) % N
            rest_w = rest_w * weights.reshape(sh)
        grids = np.meshgrid(*[folded] * (d - 1), indexing="ij")
        rest_idx = tuple(g.ravel() for g in grids)
        rest_res = rest_res.ravel()
        rest_w = rest_w.ravel()

    A = np.zeros((M,) * d, dtype=np.float64)
    for j0 in range(span):
        hits = (rest_res * int(tables[0][j0]) % N) == 1
        if not hits.any():
            continue
        idx = (np.full(int(hits.sum()), folded[j0]),) + tuple(g[hits] for g in rest_idx)
        np.add.at(A, idx, weights[j0] * rest_w[hits])
    return A


def ideal_regev_distribution_array(bases, N: int, d: int, M: int):
    """Exact output distribution of the ideal Regev circuit, as an array.

    The state before measurement is

        |psi> = (1/sqrt(M^d)) sum_x |x> |prod a_i^{x_i} mod N>

    followed by an inverse QFT_M on each of the d x-registers, giving

        p(w) = (1 / M^2d) * sum_y |sum_{x : f(x) = y} omega^{-<w,x>}|^2

    with f(x) = prod a_i^{x_i} mod N and omega = exp(2 pi i / M).

    Expanding the square turns the sum over residue classes into a sum over
    PAIRS, and f(x) = f(x') holds exactly when e = x - x' is a relation:

        sum_y |...|^2 = sum_{e in L, |e_i| < M} prod_i (M - |e_i|) omega^{-<w,e>}

    so p is one FFT of the relation-lattice autocorrelation. The naive route
    -- group the M^d exponent vectors by image, FFT each group -- computes the
    same numbers with one transform per residue class, and the class count
    grows with the order of the subgroup generated by the bases. Here the cost
    is a single transform regardless.

    Returns:
        numpy array of shape (M,)*d, indexed by w, summing to 1.
    """
    import numpy as np

    A = _relation_autocorrelation(bases, N, d, M)
    p = np.fft.fftn(A).real / float(M) ** (2 * d)
    # The lattice is symmetric (e in L iff -e in L) with symmetric weights, so
    # the transform is real up to rounding; negatives are float noise only.
    np.clip(p, 0.0, None, out=p)
    return p


def ideal_regev_distribution(bases, N: int, d: int, M: int) -> dict:
    """Exact output distribution as a dict mapping w -> probability.

    Thin wrapper over `ideal_regev_distribution_array`. Materialising all M^d
    tuple keys costs far more memory than the array itself, so prefer the
    array form for anything large; this exists for readability and for
    `total_variation_distance`.
    """
    p = ideal_regev_distribution_array(bases, N, d, M)
    return {w: float(p[w]) for w in product(range(M), repeat=d)}


def bitstring_to_regev_vector(bitstring: str, d: int, nd: int) -> tuple:
    """Decode one Qiskit measurement bitstring into a vector w in Z_M^d.

    Qiskit prints classical bits little-endian: the leftmost character is the
    highest-index clbit. Register 0 therefore occupies the RIGHTMOST nd
    characters, so the chunks are reversed after splitting.

    Spaces (which Qiskit inserts between separate classical registers) are
    stripped, so both "01010 11100" and "0101011100" decode identically.

    Defined here rather than in a simulator module so that `reference` stays
    importable with no Qiskit present.
    """
    bits = bitstring.replace(" ", "")
    if len(bits) != d * nd:
        raise ValueError(
            f"bitstring of length {len(bits)} does not match d*nd = {d * nd}"
        )
    chunks = [bits[i * nd:(i + 1) * nd] for i in range(d)]
    return tuple(int(c, 2) for c in reversed(chunks))


def counts_to_distribution(counts, d: int, nd: int) -> dict:
    """Convert Aer counts into a w -> probability dict."""
    total = sum(counts.values())
    dist = {}
    for bitstring, c in counts.items():
        w = bitstring_to_regev_vector(bitstring, d, nd)
        dist[w] = dist.get(w, 0.0) + c / total
    return dist


def total_variation_distance(p: dict, q: dict) -> float:
    """TVD between two distributions given as dicts over the same support."""
    keys = set(p) | set(q)
    return 0.5 * sum(abs(p.get(k, 0.0) - q.get(k, 0.0)) for k in keys)
